### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by TN-1** [gisikw/ksprogramming#11]
Hi!
In the next release of Kode I am planning to include support for one click library imports and I would like to include some libraries by default.
Im just asking to make sure it is ok for me to include some of your libraries, Namely Ascent, Docking, Maneuver and Rendezvous.  
Thanks in advance :)

**Comment by gisikw** [comment]
Hiya - you're welcome to, though most of these libraries still have edge-cases and such that make them rather incomplete. I'm planning on doing a pretty heavy refactor to them after the v0.19.0 release, though I'm trying to ensure this repository matches what was demo'd in the videos, even if the code is suboptimal.

Out of curiosity, are you planning to package the code with the editor? Or are you looking to set up an auto-downloader system? Just curious, as I'm doing a bit of side work on building up a package management tool for kOS, and want to avoid overlapping with your work :)

**Comment by TN-1** [comment]
Thanks! I'll keep an eye on the repo and if any changes are made ill include them in the respective releases.  
I'll be packaging it all up as part of the installer(As the Arduino IDE does).
The package manager does sound interesting though, If it's in C# and you would like a hand with it let me know, It would be useful for Kode as well as standalone.

**Comment by gisikw** [comment]
The work-in-progress I'm working on is in Ruby, as dependency resolution is a pretty challenging problem, but I'm able to leverage some of the work done on RubyGems to handle that. Alternative package models like NPM for Node.js, or NuGet for C# operate under some different constraints.

With that said, it's my intention to provide both a command-line API and a simple GUI interface, so if it turns out to be useful for folks, it might be great to bake in some support within Kode.

Cheers!

**Comment by TN-1** [comment]
Woop, Sorry! The email for your reply got buried in my inbox.

Have you started a repository for it yet? It would definitely be something I would be interested in including into Kode. In the end would you be aiming for something similar to CKAN but kOS libraries and the such instead of mods?
